const cartType = {
    DO_ADD_PRODUCT_INTO_CART: 'DO_ADD_PRODUCT_INTO_CART',
    DO_COUNT_PRODUCT_OF_CART: 'DO_COUNT_PRODUCT_OF_CART',
    SHOW_PRODUCT_CART: 'SHOW_PRODUCT_CART',
}

export default cartType