const orderType = {
    DO_CREATE_ORDER: 'DO_CREATE_ORDER',
    SHOW_ORDER_DETAIL: 'SHOW_ORDER_DETAIL',
    SHOW_UNPAID_ORDER_LIST: 'SHOW_UNPAID_ORDER_LIST',
    SHOW_PAID_ORDER_LIST: 'SHOW_PAID_ORDER_LIST',
    SHOW_PAID_ORDER_UN_RECEIVED_LIST: 'SHOW_PAID_ORDER_UN_RECEIVED_LIST'
}

export default orderType