const paypalType = {
    DO_OAUTH2_PAYPAL: 'DO_OAUTH2_PAYPAL',
    DO_CREATE_ORDER: 'DO_CREATE_ORDER',
    SHOW_ORDER: 'SHOW_ORDER',
    AUTHORIZE_PAYMENT_FOR_ORDER: 'AUTHORIZE_PAYMENT_FOR_ORD',
    CAPTURE_PAYMENT: 'CAPTURE_PAYMENT',
    SHOW_AUTHORIZE_PAYMENT: 'SHOW_AUTHORIZE_PAYMENT',
    DO_CAPTURE_ORDER: 'DO_CAPTURE_ORDER',
    DO_UPDATE_ORDER: 'DO_UPDATE_ORDER',
}

export default paypalType